import {
  analyzeShardedBenchmark,
  type RealVaultBenchmarkAggregate,
} from './realVaultBenchmark.analysis'

describe('analyzeShardedBenchmark', () => {
  it('flags benchmark observability gaps and sharded memory hotspots', () => {
    const aggregate: RealVaultBenchmarkAggregate = {
      sampledRowCount: 5000,
      queryCount: 12,
      shardCountEstimate: 3,
      avgPgliteMs: 1314.6,
      avgShardedColdMs: 75.8,
      avgShardedWarmMs: 42.9,
      avgPgliteMemoryDeltaMb: 55.2,
      avgPglitePeakRssDeltaMb: 55.2,
      avgShardedColdMemoryDeltaMb: 8.1,
      avgShardedColdPeakRssDeltaMb: 8.1,
      avgShardedWarmMemoryDeltaMb: 0.2,
      avgShardedWarmPeakRssDeltaMb: 0.2,
      avgShardedColdManifestLoadMs: 0.6,
      avgShardedColdShardPrefilterMs: 0.8,
      avgShardedColdIndexLoadMs: 3.2,
      avgShardedColdCandidateSelectionMs: 5.4,
      avgShardedColdTombstoneLoadMs: 0.9,
      avgShardedColdRowBlockLoadMs: 24.5,
      avgShardedColdVectorBlockLoadMs: 18.3,
      avgShardedColdRerankMs: 11.2,
      avgShardedColdDedupeSortMs: 0.7,
      avgShardedWarmManifestLoadMs: 0.1,
      avgShardedWarmShardPrefilterMs: 0.2,
      avgShardedWarmIndexLoadMs: 0.4,
      avgShardedWarmCandidateSelectionMs: 3.1,
      avgShardedWarmTombstoneLoadMs: 0.2,
      avgShardedWarmRowBlockLoadMs: 2.8,
      avgShardedWarmVectorBlockLoadMs: 1.9,
      avgShardedWarmRerankMs: 8.6,
      avgShardedWarmDedupeSortMs: 0.4,
      avgPgliteOverlapVsExactAtK: 0.85,
      avgPglitePathOverlapVsExactAtK: 0.9,
      avgPgliteOrderedPathPrefixMatchVsExactAtK: 0.72,
      avgPgliteRankDisplacementVsExact: 1.4,
      avgShardedOverlapVsExactAtK: 0.91,
      avgShardedPathOverlapVsExactAtK: 0.91,
      avgShardedOrderedPathPrefixMatchVsExactAtK: 0.91,
      avgShardedRankDisplacementVsExact: 0.8,
      avgShardedOverlapVsPgliteAtK: 0.93,
      avgShardedPathOverlapVsPgliteAtK: 0.93,
      avgShardedOrderedPathPrefixMatchVsPgliteAtK: 0.9,
      avgShardedRankDisplacementVsPglite: 0.7,
      pgliteTop1MatchVsExactRate: 0.83,
      shardedTop1MatchVsExactRate: 1,
      shardedTop1MatchVsPgliteRate: 1,
      pgliteFullPathOrderMatchVsExactRate: 0.58,
      shardedFullPathOrderMatchVsExactRate: 0.83,
      shardedFullPathOrderMatchVsPgliteRate: 0.58,
      buildMemoryDeltaMb: -3357.7,
      buildPeakRssDeltaMb: 2.23,
      buildDurationMs: 31988,
      pgliteIncrementalUpdateDurationMs: 2500,
      pgliteIncrementalUpdateMemoryDeltaMb: 140,
      pgliteIncrementalUpdatePeakRssDeltaMb: 120,
      pgliteIncrementalDeleteDurationMs: 900,
      pgliteIncrementalDeleteMemoryDeltaMb: 30,
      pgliteIncrementalDeletePeakRssDeltaMb: 20,
      shardedIncrementalUpdateDurationMs: 180,
      shardedIncrementalUpdateMemoryDeltaMb: 12,
      shardedIncrementalUpdatePeakRssDeltaMb: 48,
      shardedIncrementalDeleteDurationMs: 95,
      shardedIncrementalDeleteMemoryDeltaMb: 6,
      shardedIncrementalDeletePeakRssDeltaMb: 40,
      sourceRowLoadMemoryDeltaMb: -1766.07,
      pgliteLoadDurationMs: 18000,
      pgliteLoadMemoryDeltaMb: 512,
      pgliteLoadPeakRssDeltaMb: 1024,
      pgliteDumpDurationMs: 65127,
      pgliteDumpMemoryDeltaMb: -205.44,
      pgliteDumpPeakRssDeltaMb: 0,
      pgliteDumpSucceeded: true,
      pgliteDumpError: null,
      pgliteDumpGzipBytes: 608599635,
      pgliteDumpArrayBufferBytes: 608599635,
      shardedManifestLoadDurationMs: 5,
      shardedManifestLoadMemoryDeltaMb: 1,
      shardedManifestLoadPeakRssDeltaMb: 1,
    }

    const analysis = analyzeShardedBenchmark(aggregate)

    expect(analysis.benchmarkGaps).toEqual(
      expect.arrayContaining([
        expect.stringContaining('pglite dump'),
        expect.stringContaining('before/after'),
      ]),
    )
    expect(analysis.shardedImprovements).toEqual(
      expect.arrayContaining([
        expect.stringContaining('cold-query'),
        expect.stringContaining('incremental update'),
        expect.stringContaining('exact baseline'),
      ]),
    )
    expect(analysis.stageFindings).toEqual(
      expect.arrayContaining([
        expect.stringContaining('pglite load'),
        expect.stringContaining('pglite dump/save'),
        expect.stringContaining('pglite incremental update'),
        expect.stringContaining('pglite incremental delete'),
        expect.stringContaining('sharded cold query phases'),
        expect.stringContaining('dominant sharded cold-query phase'),
        expect.stringContaining('exact baseline'),
        expect.stringContaining('sharded build'),
        expect.stringContaining('sharded incremental update'),
        expect.stringContaining('sharded incremental delete'),
      ]),
    )
  })
})
